-- AlterTable
ALTER TABLE `Notificacao` MODIFY `tipo` ENUM('RECLAMACAO_PUBLICADA', 'RECLAMACAO_REJEITADA', 'RESPOSTA_OFICIAL', 'MUDANCA_STATUS', 'NOVO_COMENTARIO', 'PEDIDO_AVALIACAO', 'ATIVIDADE_SUSPEITA', 'CONTA_SEGURANCA') NOT NULL;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `senhaAlteradaEm` DATETIME(3) NULL;
